--- 

  - block: 
    # This is an ugly hack that sets the permissions correctly to g+rwX,o=rX
    # for all files that is owned by the current user that is running the playbook. 
    # We append permissions to g so that we do not override setgid flag set 
    # on some places (+s). We define permissions for others via o= as we
    # know that they shouldn't have any other permissions. 
    #
    # Note that this by purpose will miss changing the permissions of files
    # owned by an other user, as we do not want to have the playbook cluttered
    # with a lot of errors when the permission change fails.
    #
    # It is therefore expected that this script will always be run when someone is 
    # running the playbook.
    # 
    # Only for staging and production; ie for data that is to be synced to the cluster. 
    - name: set correct file permission for everything owned by current user 
      shell: "find /lupus/ngi/{conf,sw,resources} -user `whoami` -exec chmod g+rwX,o=rX {} \\;"
      when: deployment_environment != "staging" # FIXME: remove staging 

    - name: symlink deployed version to /lupus/ngi/<production|staging>/latest 
      file: src=/lupus/ngi/{{ deployment_environment }}/latest dest={{ root_path }} state=link
  - when: "deployment_environment" != "devel" 

  - debug: msg="Finished deploying to {{ root_path }}"

