qatools_repo: "https://github.com/vezzi/qaTools.git"
qatools_dest: "{{ sw_path }}/qaTools" 
qatools_version: "0af6b1df4a51518483fa8579be8b54219802a0e7"

frc_align_repo: "https://github.com/vezzi/FRC_align.git"
frc_align_dest: "{{ sw_path }}/FRCAlign"
frc_align_version: "5b3f53e01cb539c857fd4230ec9410d76220fe22"

nougat_repo: "https://github.com/SciLifeLab/NouGAT.git"
nougat_dest: "{{ sw_path }}/NouGAT"
nougat_version: "9164f6956b2308716f9ee05831f742efe9d83656"
