---

# _environment can be set to e.g. "staging" on the command line. 
# _version is then also preferably changed.
#
# This will set corresponding paths and use the appropriate port. 
arteria_siswrap_repo: https://github.com/arteria-project/arteria-siswrap.git
arteria_siswrap_version: v1.1.0
arteria_siswrap_environment: production

arteria_install_path: "{{ root_path }}/sw/arteria"

# These values will be appended with production and staging specific
# paths in the tasks.
#
# NB. The log dirs need to be created manually on destination cluster.
arteria_siswrap_env_root: "{{ arteria_install_path }}/siswrap_venv"
arteria_siswrap_sources_path: "{{ arteria_install_path }}/siswrap_src"
arteria_siswrap_config_root: "{{ ngi_pipeline_conf }}/arteria/siswrap"
arteria_siswrap_app_config: "{{ arteria_siswrap_config_root }}/app.config"
arteria_siswrap_logger_config: "{{ arteria_siswrap_config_root }}/logger.config"
arteria_siswrap_log: "{{ ngi_pipeline_upps_path }}/log/arteria/siswrap-ws"
runfolder_path: "{{ proj_root }}/{{ ngi_pipeline_upps_delivery }}/incoming/"

arteria_siswrap_port_prod: 10430
arteria_siswrap_port_stage: 10431
arteria_siswrap_mail_from: johan.hermansson@medsci.uu.se
arteria_siswrap_mail_to: arteria-project@googlegroups.com

virtual_env_command: "/usr/bin/python /lupus/ngi/irma3/virtualenv-15.0.0/virtualenv.py"

sisyphus_path: "{{ arteria_siswrap_env_root }}/deps/sisyphus/" # set by a task
sisyphus_git_repo: https://github.com/Molmed/sisyphus.git
sisyphus_repo_branch: master

# Where to install our local Perl packages
perllib_dest: "{{ ngi_resources }}/arteria/perl"

# Special $PATH variable for running some manual cpanm commands 
# which otherwie include the wrong headers and libs (e.g. from anaconda, 
# which is on the path, instead of the system libs). 
cpanm_env: /lupus/ngi/irma3/ansible-env/bin/:/usr/bin:/bin
