---
# For now, values here should be updated accordingly when user develops locally. 

# root_path should be changed to suitable value when e.g. deploying locally
# for a developer
root_path: /lupus/ngi/

# TODO: This variable has to be set to something more suitable when 
# deploying as a real user with a real home directory. This is 
# only used when building Piper atm, and will not be necessary 
# when Piper soon is available in the module system. 
home_path: /tmp 

# Name of the script that should be sourced from the user to get the 
# relevant environment variables setup. Perhaps move this to defaults vars.  
bash_env_script: sourceme_common.sh
bash_env_upps_script: sourceme_upps.sh
bash_env_sthlm_script: sourceme_sthlm.sh

ngi_pipeline_repo: https://github.com/NationalGenomicsInfrastructure/ngi_pipeline.git
ngi_pipeline_dest: "{{ root_path }}/sw/ngi_pipeline"
ngi_pipeline_version: 5550743b1848a521b0a5b0bc4b3a8b72aeeeb553
NGI_venv_name: "NGI"
ngi_pipeline_venv: "{{ root_path }}/sw/anaconda/envs/{{ NGI_venv_name }}"

ngi_pipeline_conf: "{{ root_path }}/conf/"
ngi_resources: "{{ root_path }}/resources/"

ngi_pipeline_sthlm_delivery: ngi2016003
ngi_pipeline_upps_delivery: ngi2016001
ngi_sthlm_softlinks: "/proj/{{ ngi_pipeline_sthlm_delivery }}/nobackup/NGI/softlinks"
ngi_upps_softlinks: "/proj/{{ ngi_pipeline_upps_delivery }}/nobackup/NGI/softlinks"

ngi_pipeline_sthlm_path: "/proj/{{ ngi_pipeline_sthlm_delivery }}/private/ngi_pipeline/"
ngi_pipeline_upps_path: "/proj/{{ ngi_pipeline_upps_delivery }}/private/ngi_pipeline/"

ngi_pipeline_log_sthlm: "{{ ngi_pipeline_sthlm_path }}/log/ngi_pipeline.log"
ngi_pipeline_log_upps: "{{ ngi_pipeline_upps_path }}/log/ngi_pipeline.log"

ngi_pipeline_db_upps: "{{ ngi_pipeline_upps_path }}/db/records_db_upps.sql"
ngi_pipeline_db_sthlm: "{{ ngi_pipeline_sthlm_path }}/db/records_db_sthlm.sql"

piper_version: 1.4.0
piper_src_file: /lupus/ngi/irma3/piper_src/piper-1.4.0.zip
setupfilecreator_src_file: /lupus/ngi/irma3/piper_src/setupfilecreator-1.4.0.zip
setupfilecreator_dest: "{{ root_path }}/sw/setupfilecreator"
ngi_piper_bin_dest: "{{ root_path }}/sw/piper/"

ngi_rnaseq_dest: "{{ root_path }}/sw/ngi-rnaseq"

gatk_bundle_b37_origin: "/sw/data/uppnex/reference/biodata/GATK/ftp.broadinstitute.org/bundle/2.8/b37/"
gatk_bundle_b37: "{{ ngi_resources }}/piper/gatk_bundle/2.8/b37"
# hg19 is not used, but still referenced in some config
gatk_bundle_hg19: "{{ ngi_resources }}/piper/gatk_bundle/2.8/hg19"

gatk_key: pontus.larsson_medsci.uu.se.key
statusdb_creds: statusdb_creds.yml

recipient_mail: ngi_pipeline_operators@scilifelab.se
