- name: Download anaconda
  get_url: url={{ anaconda_url }} dest={{ anaconda_src }} mode=ug+rwx checksum="sha256:{{ anaconda_checksum }}"

- name: Install anaconda
  shell: "{{ anaconda_src }} -b -p {{ anaconda_path }}"  
  args: 
    creates: "{{ anaconda_path }}/LICENSE.txt"

