---

# The steps within the comments can be effectively replaced by 'module load Nextflow'
# Currently the module has problems being automatically initialized
###

- name: Create NextFlow directory
  file: path="{{ nextflow_dest }}" state=directory mode=g+rwXs

- name: Create NextFlow installation subdirectories
  file: path="{{ nextflow_dest }}/{{ item.directory }}" state=directory mode=g+rwXs
  with_items:
  - { directory: "workfiles" }
  - { directory: "r_packages" }

- name: Download NextFlow 
  get_url: url="http://get.nextflow.io" dest="{{ nextflow_dest }}/nextflow" mode="u+rwx,g=rwx"

- name: Install NextFlow
  shell: "./nextflow"
  environment:
    NXF_LAUNCHER: "/scratch"
    NXF_HOME: "{{ nextflow_dest }}/workfiles"
    NXF_WORK: "{{ nextflow_dest }}/workfiles"
  args:
    chdir: "{{ nextflow_dest }}"

- name: Grab Nextflow version number
  shell: "ls {{ nextflow_dest }}/workfiles/framework/ | tail -1"
  register: nextflow_ver

- name: Add NextFlow to $PATH
  lineinfile: dest="{{ ngi_pipeline_conf }}/{{ bash_env_script }}"
              line="export PATH={{ root_path }}/sw/nextflow:$PATH"
              backup=no
###

# Change target to {{ ngi_rnaseq_dest }} when using module system
- name: Add Nextflow module vars to sourceme
  lineinfile: dest={{ ngi_pipeline_conf }}/{{ bash_env_script }}
              line="{{ item.envvar }}"
              backup=no
  with_items:
  - { envvar: "export SNIC_TMP=/scratch"}
  - { envvar: "export NXF_OPTS='-Xms1g -Xmx4g'"}
  - { envvar: "export NXF_VER={{ nextflow_ver.stdout }}"}
  - { envvar: "export NXF_HOME={{ nextflow_dest }}/workfiles"}
  - { envvar: "export NXF_WORK={{ nextflow_dest }}/workfiles"}
  - { envvar: "export NXF_TEMP=${SNIC_TMP:-{{ nextflow_dest }}/workfiles}"}
  - { envvar: "export NXF_LAUNCHBASE=${SNIC_TMP:-{{ nextflow_dest }}/workfiles}"}
# Defines where the classpath file ends up
  - { envvar: "export NXF_LAUNCHER=${SNIC_TMP:-{{ nextflow_dest }}/workfiles}"}

- name: Copy R dependencies script
  copy:
    src: "files/install_R_dependencies.r"
    dest: "{{ nextflow_dest }}/r_packages"
 
- name: Run R script to install dependencies
  command: "Rscript install_R_dependencies.r"
  environment:
    R_LIBS_USER: "{{ nextflow_dest }}/r_packages"
  args:
    chdir: "{{ nextflow_dest }}/r_packages"
