---
- name: Fetch NGI-RNAseq from GitHub
  git: repo="{{ ngi_rnaseq_repo }}"
       dest="{{ ngi_rnaseq_dest }}"
       version="{{ ngi_rnaseq_version }}"
       force=yes

- name: Copy NGI-RNAseq config
  template: src="ngi-rnaseq.config.j2" dest="{{ ngi_pipeline_conf }}/ngi-rnaseq_{{ item.site }}.config"
  with_items:
  - { site: "sthlm", proj: "{{ ngi_pipeline_sthlm_delivery }}" }
  - { site: "upps", proj: "{{ ngi_pipeline_upps_delivery }}" }
