---
- name: Fetch NGI-RNAseq from GitHub
  git: repo="{{ ngi_rnaseq_repo }}"
       dest="{{ ngi_rnaseq_dest }}"
       version="{{ ngi_rnaseq_version }}"
       force=yes

- name: Copy NGI-RNAseq config
  template: src="ngi-rnaseq.config.j2" dest="{{ ngi_pipeline_conf }}/ngi-rnaseq_{{ item.site }}.config"
  with_items:
  - { site: "sthlm", proj: "{{ ngi_pipeline_sthlm_delivery }}" }
  - { site: "upps", proj: "{{ ngi_pipeline_upps_delivery }}" }

- name: Add Nextflow module vars to sourceme
  lineinfile: dest={{ ngi_pipeline_conf }}/{{ bash_env_script }}
              line="{{ item.envvar }}"
  with_items:
  - { envvar: "export NXF_HOME=$HOME/.nextflow" }
  - { envvar: "export NXF_OPTS='-Xms1g -Xmx4g'"}
  - { envvar: "export NXF_TEMP=${SNIC_TMP:-$NXF_HOME/tmp}"}
  - { envvar: "export NXF_WORK=$NXF_HOME/work"}
  - { envvar: "export NXF_LAUNCHBASE=${SNIC_TMP:-$NXF_HOME/tmp}"}
