---
- name: create virtual python env for arteria-delivery 
  shell: "{{ conda_bin }} create --name arteria-delivery python=3.6"
  args: 
    creates: "{{ arteria_delivery_env_root }}"

- name: get arteria-delivery from git
  git:
    repo: "{{ arteria_delivery_repo }}"
    dest: "{{ arteria_delivery_sources_path }}"
    version: "{{ arteria_delivery_version }}"

- name: install arteria-delivery requirements
  pip:
      requirements: "{{ arteria_delivery_sources_path }}/requirements/dev"
      chdir: "{{ arteria_delivery_sources_path }}"
      virtualenv: "{{ arteria_delivery_env_root }}"
      state: present
      extra_args: "-U"

- name: install arteria-delivery
  pip:
      name: .
      chdir: "{{ arteria_delivery_sources_path }}"
      virtualenv: "{{ arteria_delivery_env_root }}"
      state: present
      extra_args: "-U"

